export interface Trip {
  slug: string;
  title: string;
  duration: string;
  desc: string;
  img: string;
  price: string;
  cat: string;
  dest: string;
  itinerary: { day: string; activities: string }[];
  places: string[];
  included: string[];
  excluded: string[];
  bestTime: string;
  tips: string[];
  gallery: string[];
}

export const allTrips: Trip[] = [
  {
    slug: "goa-beach-tour",
    title: "Goa Beach Tour",
    duration: "3 Days",
    desc: "Beaches, Water Sports & Nightlife",
    img: "https://images.unsplash.com/photo-1514539079130-25950c84af65?w=800&q=80",
    price: "₹8,499",
    cat: "Domestic",
    dest: "Goa",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Goa airport/railway station. Check into beach resort. Evening at Baga Beach. Dinner at beachside shack." },
      { day: "Day 2", activities: "Breakfast. North Goa tour — Calangute, Anjuna & Vagator beaches. Water sports at Candolim. Optional: casino night." },
      { day: "Day 3", activities: "Breakfast. South Goa tour — Colva & Palolem beaches. Visit Basilica of Bom Jesus. Departure with memories." },
    ],
    places: ["Baga Beach", "Calangute", "Anjuna", "Vagator", "Candolim Water Sports", "Colva Beach", "Palolem Beach", "Basilica of Bom Jesus"],
    included: ["Hotel accommodation with breakfast", "Airport/station transfers", "AC vehicle for sightseeing", "All permits & toll taxes", "Experienced driver"],
    excluded: ["Flight/train tickets", "Lunch & dinner", "Water sports charges", "Entry fees to monuments", "Personal expenses"],
    bestTime: "November to February",
    tips: ["Carry sunscreen and hats", "Try local seafood", "Book water sports in advance", "Stay hydrated"],
    gallery: [
      "https://images.unsplash.com/photo-1514539079130-25950c84af65?w=800&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
      "https://images.unsplash.com/photo-1494783367193-149034c05e8f?w=800&q=80",
    ],
  },
  {
    slug: "kashmir-paradise",
    title: "Kashmir Paradise",
    duration: "5 Days",
    desc: "Snow, Mountains & Houseboats",
    img: "https://images.unsplash.com/photo-1592659762303-90081d34b277?w=800&q=80",
    price: "₹15,999",
    cat: "Domestic",
    dest: "Kashmir",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Srinagar airport. Check into houseboat on Dal Lake. Evening Shikara ride." },
      { day: "Day 2", activities: "Full-day Srinagar sightseeing — Mughal Gardens (Shalimar, Nishat), Shankaracharya Temple. Local market shopping." },
      { day: "Day 3", activities: "Drive to Gulmarg. Gondola ride (cable car). Snow activities & skiing. Overnight in Gulmarg." },
      { day: "Day 4", activities: "Drive to Pahalgam. Visit Betaab Valley, Aru Valley & Chandanwari. Horse riding. Overnight in Pahalgam." },
      { day: "Day 5", activities: "Breakfast. Drive back to Srinagar. Departure with beautiful memories." },
    ],
    places: ["Dal Lake", "Mughal Gardens", "Shankaracharya Temple", "Gulmarg", "Gondola Ride", "Pahalgam", "Betaab Valley", "Aru Valley"],
    included: ["Hotel/houseboat stay with meals", "All transfers in AC vehicle", "Shikara ride", "Gondola ride tickets", "Driver & guide"],
    excluded: ["Flight tickets", "Skiing charges", "Horse riding charges", "Personal expenses", "Tips"],
    bestTime: "April to October (summer), December to February (snow)",
    tips: ["Carry warm clothes even in summer", "Try Kashmiri Wazwan", "Buy saffron & dry fruits", "Book houseboat in advance"],
    gallery: [
      "https://images.unsplash.com/photo-1592659762303-90081d34b277?w=800&q=80",
      "https://images.unsplash.com/photo-1566837945700-30057527ade0?w=800&q=80",
      "https://images.unsplash.com/photo-1597432538819-3a78f26c9adc?w=800&q=80",
    ],
  },
  {
    slug: "kerala-backwaters",
    title: "Kerala Backwaters",
    duration: "4 Days",
    desc: "Houseboat, Ayurveda & Nature",
    img: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&q=80",
    price: "₹12,499",
    cat: "Domestic",
    dest: "Kerala",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Kochi airport. Visit Fort Kochi & Chinese Fishing Nets. Evening Kathakali performance." },
      { day: "Day 2", activities: "Drive to Munnar. En route visit Cheeyappara & Valara waterfalls. Check into hill station resort." },
      { day: "Day 3", activities: "Munnar sightseeing — Tea Gardens, Eravikulam National Park, Mattupetty Dam. Photo point visits." },
      { day: "Day 4", activities: "Drive to Alleppey. Board deluxe houseboat. Cruise through backwaters with lunch & dinner onboard. Overnight on houseboat." },
    ],
    places: ["Fort Kochi", "Chinese Fishing Nets", "Munnar Tea Gardens", "Eravikulam National Park", "Alleppey Backwaters", "Houseboat Cruise"],
    included: ["Hotel/houseboat stay", "All meals on houseboat", "AC vehicle for transfers", "Houseboat cruise", "Sightseeing as per itinerary"],
    excluded: ["Flight tickets", "Ayurveda massages", "Entry fees to parks", "Camera fees", "Personal expenses"],
    bestTime: "September to March",
    tips: ["Try Kerala Sadya", "Book Ayurveda massage in advance", "Monsoon season is beautiful too", "Carry mosquito repellent"],
    gallery: [
      "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&q=80",
      "https://images.unsplash.com/photo-1597575732215-85c7d9747c5a?w=800&q=80",
      "https://images.unsplash.com/photo-1593113630400-ea4288922497?w=800&q=80",
    ],
  },
  {
    slug: "ladakh-adventure",
    title: "Ladakh Adventure",
    duration: "6 Days",
    desc: "Bike Ride, Mountains & Monasteries",
    img: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&q=80",
    price: "₹18,999",
    cat: "Adventure",
    dest: "Ladakh",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Leh airport. Acclimatization & rest. Evening walk around Leh market." },
      { day: "Day 2", activities: "Leh sightseeing — Leh Palace, Shanti Stupa, Magnetic Hill, Sangam (Indus & Zanskar rivers)." },
      { day: "Day 3", activities: "Drive to Nubra Valley via Khardungla Pass (highest motorable road). Camel safari at Hunder." },
      { day: "Day 4", activities: "Explore Nubra — Diskit Monastery, Hunder Sand Dunes. Drive back to Leh." },
      { day: "Day 5", activities: "Drive to Pangong Lake via Changla Pass. Enjoy the breathtaking blue lake. Overnight near lake." },
      { day: "Day 6", activities: "Sunrise at Pangong. Drive back to Leh. Departure." },
    ],
    places: ["Leh Palace", "Shanti Stupa", "Khardungla Pass", "Nubra Valley", "Pangong Lake", "Magnetic Hill", "Diskit Monastery"],
    included: ["Hotel/camp stay with meals", "Inner line permits", "AC vehicle for sightseeing", "Oxygen cylinders", "Experienced driver/guide"],
    excluded: ["Flight tickets", "Bike rental (if self-drive)", "Camel safari charges", "Personal expenses", "Insurance"],
    bestTime: "May to September",
    tips: ["Acclimatize for 1-2 days", "Carry medicines for altitude sickness", "Stay hydrated", "Carry sunscreen & sunglasses"],
    gallery: [
      "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&q=80",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    ],
  },
  {
    slug: "manali-escape",
    title: "Manali Escape",
    duration: "4 Days",
    desc: "Adventure, Snow & Scenic Views",
    img: "https://images.unsplash.com/photo-1715686729965-e96dd71a8e61?w=800&q=80",
    price: "₹10,999",
    cat: "Domestic",
    dest: "Manali",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Chandigarh/Bhuntar. Drive to Manali. Check into hotel. Evening walk on Mall Road." },
      { day: "Day 2", activities: "Full-day Manali sightseeing — Hadimba Temple, Manu Temple, Tibetan Monastery, Vashist Hot Springs." },
      { day: "Day 3", activities: "Drive to Solang Valley. Snow activities — skiing, paragliding, zorbing. Visit Club House." },
      { day: "Day 4", activities: "Optional Rohtang Pass visit (if open). Departure with memories." },
    ],
    places: ["Mall Road", "Hadimba Temple", "Manu Temple", "Vashist Hot Springs", "Solang Valley", "Rohtang Pass", "Tibetan Monastery"],
    included: ["Hotel stay with breakfast & dinner", "AC vehicle for sightseeing", "Airport/station transfers", "Driver allowance", "All taxes"],
    excluded: ["Flight/train tickets", "Snow activities charges", "Rohtang Pass permit", "Personal expenses", "Tips"],
    bestTime: "October to February (snow), March to June (summer)",
    tips: ["Carry warm clothes", "Check Rohtang Pass availability", "Try local trout fish", "Book paragliding in advance"],
    gallery: [
      "https://images.unsplash.com/photo-1715686729965-e96dd71a8e61?w=800&q=80",
      "https://images.unsplash.com/photo-1582653291997-079a1c04e2a1?w=800&q=80",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    ],
  },
  {
    slug: "ooty-coonoor",
    title: "Ooty & Coonoor",
    duration: "3 Days",
    desc: "Hills, Nature & Tea Gardens",
    img: "https://images.unsplash.com/photo-1582653291997-079a1c04e2a1?w=800&q=80",
    price: "₹7,999",
    cat: "Weekend",
    dest: "Ooty",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Mettupalayam railway station. Board Nilgiri Mountain Railway (UNESCO). Reach Ooty. Check into resort." },
      { day: "Day 2", activities: "Ooty sightseeing — Botanical Gardens, Ooty Lake (boating), Doddabetta Peak, Rose Garden." },
      { day: "Day 3", activities: "Drive to Coonoor. Visit Sim's Park, Lamb's Rock, Tea Factory. Departure." },
    ],
    places: ["Nilgiri Mountain Railway", "Botanical Gardens", "Ooty Lake", "Doddabetta Peak", "Rose Garden", "Coonoor", "Sim's Park", "Tea Factory"],
    included: ["Hotel stay with breakfast", "Toy train tickets", "AC vehicle for sightseeing", "All permits", "Driver"],
    excluded: ["Flight/train tickets to Mettupalayam", "Lunch & dinner", "Boat charges", "Personal expenses"],
    bestTime: "Throughout the year (best: March to June & October to December)",
    tips: ["Book toy train tickets early", "Carry jackets as weather is cool", "Visit tea estates", "Try homemade chocolates"],
    gallery: [
      "https://images.unsplash.com/photo-1582653291997-079a1c04e2a1?w=800&q=80",
      "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&q=80",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    ],
  },
  {
    slug: "bali-honeymoon",
    title: "Bali Honeymoon",
    duration: "6 Days",
    desc: "Beaches, Resorts & Culture",
    img: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    price: "₹45,999",
    cat: "International",
    dest: "Bali",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Bali airport. Transfer to resort. Evening beach walk & welcome dinner." },
      { day: "Day 2", activities: "South Bali tour — Uluwatu Temple, Padang Padang Beach, Jimbaran Bay sunset dinner." },
      { day: "Day 3", activities: "Ubud tour — Tegallalang Rice Terraces, Monkey Forest, Ubud Palace, Art Market." },
      { day: "Day 4", activities: "Water sports day — Snorkeling, banana boat ride, parasailing at Tanjung Benoa." },
      { day: "Day 5", activities: "Free day for shopping & spa. Optional: Tanah Lot Temple sunset." },
      { day: "Day 6", activities: "Breakfast. Transfer to airport. Departure." },
    ],
    places: ["Uluwatu Temple", "Padang Padang Beach", "Ubud", "Tegallalang Rice Terraces", "Tanah Lot", "Jimbaran Bay", "Tanjung Benoa"],
    included: ["Hotel/resort stay with breakfast", "Airport transfers", "AC vehicle for tours", "English-speaking guide", "Water sports (2 activities)"],
    excluded: ["International flights", "Visa fees", "Lunch & dinner (except welcome dinner)", "Spa charges", "Personal expenses"],
    bestTime: "April to October",
    tips: ["Carry USD for easier exchange", "Dress modestly at temples", "Try local Balinese massage", "Bargain at markets"],
    gallery: [
      "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
      "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&q=80",
      "https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?w=800&q=80",
    ],
  },
  {
    slug: "thailand-tour",
    title: "Thailand Tour",
    duration: "5 Days",
    desc: "Bangkok, Pattaya & Islands",
    img: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80",
    price: "₹35,999",
    cat: "International",
    dest: "Thailand",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Bangkok airport. City tour — Grand Palace, Wat Pho, Wat Arun. Evening Khao San Road." },
      { day: "Day 2", activities: "Shopping day — Siam Paragon, Chatuchak Market. Evening Chao Phraya dinner cruise." },
      { day: "Day 3", activities: "Drive to Pattaya. Visit Sanctuary of Truth, Pattaya Beach. Alcazar Cabaret Show." },
      { day: "Day 4", activities: "Coral Island tour — Snorkeling, parasailing, beach activities. Evening Walking Street." },
      { day: "Day 5", activities: "Breakfast. Transfer to Bangkok airport. Departure." },
    ],
    places: ["Grand Palace", "Wat Pho", "Wat Arun", "Chatuchak Market", "Pattaya Beach", "Coral Island", "Sanctuary of Truth"],
    included: ["Hotel stay with breakfast", "Airport transfers", "AC vehicle for tours", "Bangkok-Pattaya transfers", "Coral Island ferry"],
    excluded: ["International flights", "Visa fees", "Lunch & dinner", "Cabaret show tickets", "Personal expenses"],
    bestTime: "November to February",
    tips: ["Get visa on arrival (easy)", "Use Grab taxis", "Try Thai street food", "Stay hydrated in heat"],
    gallery: [
      "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80",
      "https://images.unsplash.com/photo-1562597728-93fde2b7a709?w=800&q=80",
      "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80",
    ],
  },
  {
    slug: "dubai-luxury",
    title: "Dubai Luxury",
    duration: "5 Days",
    desc: "Shopping, Desert Safari & Burj",
    img: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
    price: "₹55,999",
    cat: "International",
    dest: "Dubai",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Dubai airport. Check into hotel. Evening Dubai Marina walk & dinner." },
      { day: "Day 2", activities: "Dubai city tour — Burj Khalifa (observation deck), Dubai Mall, Dubai Fountain show." },
      { day: "Day 3", activities: "Desert Safari — Dune bashing, camel ride, BBQ dinner & belly dance show." },
      { day: "Day 4", activities: "Day at leisure. Optional: Atlantis Aquaventure Park, Miracle Garden, or Gold Souk." },
      { day: "Day 5", activities: "Breakfast. Transfer to airport. Departure." },
    ],
    places: ["Burj Khalifa", "Dubai Mall", "Dubai Marina", "Desert Safari", "Palm Jumeirah", "Dubai Fountain", "Gold Souk"],
    included: ["Hotel stay with breakfast", "Airport transfers", "City tour with guide", "Desert safari with dinner", "Burj Khalifa tickets"],
    excluded: ["International flights", "Visa fees", "Lunch & dinner (except desert safari)", "Optional tours", "Personal expenses"],
    bestTime: "November to March",
    tips: ["Carry light woolens (malls are cold)", "Respect local customs", "Use metro to save on taxis", "Book Burj Khalifa tickets in advance"],
    gallery: [
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
      "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&q=80",
      "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=800&q=80",
    ],
  },
  {
    slug: "rishikesh-rafting",
    title: "Rishikesh Rafting",
    duration: "3 Days",
    desc: "Rafting, Camping & Yoga",
    img: "https://images.unsplash.com/photo-1540202404-a2f29016b523?w=800&q=80",
    price: "₹6,999",
    cat: "Adventure",
    dest: "Rishikesh",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Rishikesh. Check into riverside camp. Evening Ganga Aarti at Triveni Ghat." },
      { day: "Day 2", activities: "Morning yoga session. 16km white water rafting (Class III-IV rapids). Cliff jumping, body surfing. Evening bonfire." },
      { day: "Day 3", activities: "Breakfast. Visit Laxman Jhula & Ram Jhula. Optional bungee jumping. Departure." },
    ],
    places: ["Triveni Ghat", "Laxman Jhula", "Ram Jhula", "Shivpuri (rafting start point)", "Beatles Ashram", "Neer Garh Waterfall"],
    included: ["Camp stay with meals", "Rafting equipment & guide", "Yoga session", "Bonfire", "All safety gear"],
    excluded: ["Transport to Rishikesh", "Bungee jumping", "Personal expenses", "Tips"],
    bestTime: "September to June",
    tips: ["Wear quick-dry clothes for rafting", "Carry extra change of clothes", "Avoid heavy meals before rafting", "Try local Ganga beach cafes"],
    gallery: [
      "https://images.unsplash.com/photo-1540202404-a2f29016b523?w=800&q=80",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    ],
  },
  {
    slug: "andaman-islands",
    title: "Andaman Islands",
    duration: "5 Days",
    desc: "Beaches, Snorkeling & Sunsets",
    img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    price: "₹22,999",
    cat: "Honeymoon",
    dest: "Andaman",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Port Blair. Visit Cellular Jail. Evening light & sound show." },
      { day: "Day 2", activities: "Ferry to Havelock Island. Check into beach resort. Evening at Radhanagar Beach (Asia's best)." },
      { day: "Day 3", activities: "Snorkeling at Elephant Beach. Optional scuba diving. Beachside dinner." },
      { day: "Day 4", activities: "Ferry to Neil Island. Visit Bharatpur Beach & Laxmanpur Beach. Natural bridge." },
      { day: "Day 5", activities: "Return to Port Blair. Departure." },
    ],
    places: ["Cellular Jail", "Havelock Island", "Radhanagar Beach", "Elephant Beach", "Neil Island", "Bharatpur Beach", "Natural Bridge"],
    included: ["Hotel/resort stay with breakfast", "Ferry transfers", "Snorkeling gear & guide", "AC vehicle on Port Blair", "All entry permits"],
    excluded: ["Flight tickets", "Scuba diving charges", "Lunch & dinner", "Personal expenses", "Tips"],
    bestTime: "October to May",
    tips: ["Book ferries in advance", "Carry snorkeling gear if possible", "Try fresh seafood", "Visit during weekdays to avoid crowds"],
    gallery: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
      "https://images.unsplash.com/photo-1514539079130-25950c84af65?w=800&q=80",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    ],
  },
  {
    slug: "mysore-coorg",
    title: "Mysore & Coorg",
    duration: "3 Days",
    desc: "Palace, Coffee Plantations & Hills",
    img: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80",
    price: "₹6,499",
    cat: "Weekend",
    dest: "Mysore",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Mysore. Visit Mysore Palace & Brindavan Gardens. Evening light show." },
      { day: "Day 2", activities: "Drive to Coorg. Visit coffee plantations, Abbey Falls, Dubare Elephant Camp." },
      { day: "Day 3", activities: "Trek to Tadiandamol peak. Visit Tibetan Monastery. Departure." },
    ],
    places: ["Mysore Palace", "Brindavan Gardens", "Abbey Falls", "Dubare Elephant Camp", "Coffee Plantations", "Tadiandamol Peak", "Golden Temple"],
    included: ["Hotel stay with breakfast", "AC vehicle for sightseeing", "Plantation tour", "All taxes"],
    excluded: ["Lunch & dinner", "Elephant ride charges", "Personal expenses", "Tips"],
    bestTime: "September to March",
    tips: ["Try Coorg coffee & honey", "Visit during monsoon for lush greenery", "Book palace tickets online", "Carry light woolens"],
    gallery: [
      "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
      "https://images.unsplash.com/photo-1582653291997-079a1c04e2a1?w=800&q=80",
    ],
  },
  {
    slug: "tirupati-pilgrimage",
    title: "Tirupati Pilgrimage",
    duration: "2 Days",
    desc: "Temple Visit & Spiritual Journey",
    img: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80",
    price: "₹4,999",
    cat: "Pilgrimage",
    dest: "Tirupati",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Tirupati. Check into hotel. Evening darshan at Sri Venkateswara Temple (if tickets available)." },
      { day: "Day 2", activities: "Morning darshan. Visit Sri Padmavathi Temple & Kapila Theertham. Departure." },
    ],
    places: ["Sri Venkateswara Temple", "Tirumala", "Sri Padmavathi Temple", "Kapila Theertham", "Talakona Waterfalls"],
    included: ["Hotel stay with breakfast", "Tirumala transfers", "AC vehicle", "Darshan assistance"],
    excluded: ["Flight/train tickets", "Special darshan tickets", "Lunch & dinner", "Personal expenses"],
    bestTime: "Throughout the year",
    tips: ["Book darshan tickets online in advance", "Avoid weekends for less crowd", "Carry umbrella (rain common)", "Donate to Hundi for blessings"],
    gallery: [
      "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80",
      "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80",
      "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80",
    ],
  },
  {
    slug: "varanasi-spiritual",
    title: "Varanasi Spiritual",
    duration: "3 Days",
    desc: "Ganga Aarti, Temples & Culture",
    img: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80",
    price: "₹7,999",
    cat: "Pilgrimage",
    dest: "Varanasi",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Varanasi. Check into hotel. Evening Ganga Aarti at Dashashwamedh Ghat. Boat ride." },
      { day: "Day 2", activities: "Sunrise boat ride on Ganges. Visit Kashi Vishwanath Temple, Sarnath (Buddhist site). Banaras silk shopping." },
      { day: "Day 3", activities: "Visit Tulsi Manas Temple & Ramnagar Fort. Optional Assi Ghat walk. Departure." },
    ],
    places: ["Dashashwamedh Ghat", "Kashi Vishwanath Temple", "Sarnath", "Assi Ghat", "Tulsi Manas Temple", "Ramnagar Fort", "Banaras Silk Market"],
    included: ["Hotel stay with breakfast", "Boat rides", "AC vehicle for sightseeing", "Ganga Aarti viewing", "Guide"],
    excluded: ["Flight/train tickets", "Lunch & dinner", "Silk purchases", "Camera fees at temples", "Personal expenses"],
    bestTime: "October to March",
    tips: ["Wear comfortable walking shoes", "Keep valuables safe in crowds", "Try Banarasi paan & kachori", "Attend both evening & morning aarti"],
    gallery: [
      "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80",
      "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80",
      "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80",
    ],
  },
  {
    slug: "rajasthan-heritage",
    title: "Rajasthan Heritage",
    duration: "6 Days",
    desc: "Palaces, Forts & Desert Safari",
    img: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80",
    price: "₹16,999",
    cat: "Family",
    dest: "Rajasthan",
    itinerary: [
      { day: "Day 1", activities: "Arrival at Jaipur. Check into hotel. Evening visit Birla Temple & local bazaar." },
      { day: "Day 2", activities: "Jaipur sightseeing — Amber Fort, Hawa Mahal, City Palace, Jantar Mantar. Elephant ride at Amber." },
      { day: "Day 3", activities: "Drive to Jodhpur. Visit Mehrangarh Fort, Jaswant Thada, Umaid Bhawan Palace. Blue city walk." },
      { day: "Day 4", activities: "Drive to Udaipur via Ranakpur Jain Temple. Evening boat ride on Lake Pichola." },
      { day: "Day 5", activities: "Udaipur sightseeing — City Palace, Jag Mandir, Saheliyon Ki Bari. Sunset at Sajjangarh Fort." },
      { day: "Day 6", activities: "Breakfast. Transfer to Udaipur airport. Departure." },
    ],
    places: ["Amber Fort", "Hawa Mahal", "City Palace Jaipur", "Mehrangarh Fort", "Lake Pichola", "City Palace Udaipur", "Ranakpur Temple"],
    included: ["Hotel stay with breakfast", "AC vehicle for all transfers", "Elephant ride at Amber", "Boat ride at Udaipur", "Experienced guide"],
    excluded: ["Flight/train tickets", "Lunch & dinner", "Desert safari charges", "Monument entry fees", "Personal expenses"],
    bestTime: "October to March",
    tips: ["Carry sun protection", "Try Dal Baati Churma", "Bargain in local markets", "Book heritage hotels for experience"],
    gallery: [
      "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80",
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80",
      "https://images.unsplash.com/photo-1514539079130-25950c84af65?w=800&q=80",
    ],
  },
];
